export const LOGIN_USER = 'LOGIN_USER'

export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'

export const FETCH_LEEDS_START = 'FETCH_LEEDS_START'
export const FETCH_LEEDS_SUCCES = 'FETCH_LEEDS_SUCCES'
export const FETCH_LEEDS_ERROR = 'FETCH_LEEDS_ERROR'

export const FETCH_QUOTES_START = 'FETCH_QUOTES_START'
export const FETCH_QUOTES_SUCCES = 'FETCH_QUOTES_SUCCES'
export const FETCH_QUOTES_ERROR = 'FETCH_QUOTES_ERROR'

export const QUOTES_POST_SUCCESS = 'QUOTES_POST_SUCCESS'