export const LOGIN_USER = 'LOGIN_USER'

export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'

export const FETCH_LEEDS_START = 'FETCH_LEEDS_START'
export const FETCH_LEEDS_SUCCES = 'FETCH_LEEDS_SUCCES'
export const FETCH_LEEDS_ERROR = 'FETCH_LEEDS_ERROR'

export const FETCH_QUOTES_START = 'FETCH_QUOTES_START'
export const FETCH_QUOTES_SUCCES = 'FETCH_QUOTES_SUCCES'
export const FETCH_QUOTES_ERROR = 'FETCH_QUOTES_ERROR'

export const QUOTES_POST_SUCCESS = 'QUOTES_POST_SUCCESS'
export const QUOTES_DELETE_SUCCESS = 'QUOTES_DELETE_SUCCESS'
export const QUOTES_PATCH_SUCCESS = 'QUOTES_PATCH_SUCCESS'

export const TASKS_FETCH_START = 'TASKS_FETCH_START'
export const TASKS_FETCH_SUCCESS = 'TASKS_FETCH_SUCCESS'
export const TASKS_FETCH_ERROR = 'TASKS_FETCH_ERROR'

export const TASKS_POST_SUCCESS = 'TASKS_POST_SUCCESS'

export const FETCH_CHEAT_SHEET_SECTION_START = 'FETCH_CHEAT_SHEET_SECTION_START'
export const FETCH_CHEAT_SHEET_SECTION_SUCCESS = 'FETCH_CHEAT_SHEET_SECTION_SUCCESS'
export const FETCH_CHEAT_SHEET_SECTION_ERROR = 'FETCH_CHEAT_SHEET_SECTION_ERROR'

export const FETCH_CHEAT_SHEET_SECTION_POST_SUCCESS = 'FETCH_CHEAT_SHEET_SECTION_POST_SUCCESS'

export const FETCH_CHEAT_SHEET_THEMES_START = 'FETCH_CHEAT_SHEET_THEMES_START'
export const FETCH_CHEAT_SHEET_THEMES_SUCCESS = 'FETCH_CHEAT_SHEET_THEMES_SUCCESS'
export const FETCH_CHEAT_SHEET_THEMES_ERROR = 'FETCH_CHEAT_SHEET_THEMES_ERROR'

export const CHEAT_SHEET_THEMES_POST = 'CHEAT_SHEET_THEMES_POST'

export const RENDER_OPTIONS_SUCCESS = 'RENDER_OPTIONS_SUCCESS'

export const LOGOUT_USER = 'LOGOUT_USER'
